describe("Verify the Checkout functionality", () => {
    it('It should verify the checkout functionality', () => {
        cy.visit('https://www.saucedemo.com/')
        cy.get('#user-name').type('standard_user')
        cy.get('#password').type('secret_sauce')
        cy.get('#login-button').click()
        cy.url().should('include', '/inventory.html')
        cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
        cy.get('[data-test="shopping-cart-badge"]').should('have.text', '1')
        cy.get('.shopping_cart_link').click()
        cy.url().should('include', '/cart.html')
        cy.get('[data-test="inventory-item"]').should('have.length', 1)
        cy.get('[data-test="checkout"]').click()
        cy.url().should('include', '/checkout-step-one.html')
    })
})
describe("Verify the Checkout functionality with valid data", () => {
    it('It should verify the checkout functionality with valid data', () => {
        cy.visit('https://www.saucedemo.com/')
        cy.get('#user-name').type('standard_user')
        cy.get('#password').type('secret_sauce')
        cy.get('#login-button').click()
        cy.url().should('include', '/inventory.html')
        cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
        cy.get('[data-test="shopping-cart-badge"]').should('have.text', '1')
        cy.get('.shopping_cart_link').click()
        cy.url().should('include', '/cart.html')
        cy.get('[data-test="inventory-item"]').should('have.length', 1)
        cy.get('[data-test="checkout"]').click()
        cy.url().should('include', '/checkout-step-one.html')
        cy.get('[data-test="firstName"]').type('John')
        cy.get('[data-test="lastName"]').type('Doe')
        cy.get('[data-test="postalCode"]').type('12345')
        cy.get('[data-test="continue"]').click()
        cy.url().should('include', '/checkout-step-two.html')
        cy.get('[data-test="finish"]').click()
        cy.url().should('include', '/checkout-complete.html')
        cy.get('.complete-header').should('have.text', 'Thank you for your order!')
    })
})